--[[
    File for controlling train movements
]]

local train = require(script.Parent.train_movement)
local nodes = game.Workspace:WaitForChild("train").train_nodes

function make_positions()
    --[[
        Generats a circle of nodes for the train to follow

        Partially generated by google bard
    ]]
    local positions = {}
    local radius = 100
    for angle = 0, 360, 1 do
      local x = radius * math.cos(angle * math.pi / 180)
      local z = radius * math.sin(angle * math.pi / 180)
      table.insert(positions, Vector3.new(x, 0, z))
    end
    for index, position in positions do
      local part = Instance.new("Part")
      part.Position = position
      part.Parent = nodes
      part.Anchored = true
    end
end

make_positions()

local nodelist = {}
print("node children: ")
print(nodes:GetChildren())
for k,v in nodes:GetChildren() do
	table.insert(nodelist, v)
end

while true do 
	train:move_to_nodes(nodelist)
end