--[[
    File for controlling train movements
]]

local train = require(script.Parent.train_movement)
local nodes = game.Workspace:WaitForChild("train").train_nodes

function make_positions()
  --[[
      Generates a circle of nodes for the train to follow

      Partially generated by google bard
  ]]
  local positions = {}
  local radius = 300
  local offset = 200
  local num_nodes = 800
  local step = 360 / num_nodes

  for angle = 0, 360, step do
    local x = radius * math.cos(angle * math.pi / 180) + offset
    local z = radius * math.sin(angle * math.pi / 180) + offset
    table.insert(positions, Vector3.new(x, 0, z))
  end

  for index, position in ipairs(positions) do
    local part = Instance.new("Part")
    part.Position = position
    part.Parent = nodes
    part.Anchored = true
    part.Transparency = 1
  end
end

make_positions()


local nodelist = {}
for k,v in nodes:GetChildren() do
	table.insert(nodelist, v)
end



function do_node_thing(cart, parent)
  coroutine.wrap(function()
    if not parent then
      while true do
        cart:move_to_nodes(nodelist)
      end
        
    else 
      while true do
        cart:move_to_node(parent.child_node, nodelist)
      end
    end
  end)()
end

function spawn_train(length)
  local head = train.new()
  local carts = {}
  
  table.insert(carts, head)
  do_node_thing(head)

  for i = 2, length do
    local cart = train.new()
    do_node_thing(cart, carts[i-1])
    carts[#carts + 1] = cart
  end
end

spawn_train(10)

print("done making carts")